# Generated by Django 3.1.3 on 2020-12-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seymaterial',
            fields=[
                ('mno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('mname', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seyvalue',
            fields=[
                ('vno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('vinp', models.IntegerField(null=True)),
                ('vsey', models.FloatField(null=True)),
                ('vposi', models.FloatField(null=True)),
                ('vnega', models.FloatField(null=True)),
                ('manum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sey_select.seymaterial')),
            ],
        ),
    ]
