# Generated by Django 3.1.3 on 2020-12-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sey_select', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seytext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='二次电子发射系数')),
                ('upload_data', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('textnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sey_select.seymaterial')),
            ],
        ),
    ]
